// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyD6_I5YiZycrIFYEYQo4jA-yIKRKjTxGzg",
      authDomain: "professional-voice-assistant.firebaseapp.com",
      projectId: "professional-voice-assistant",
      storageBucket: "professional-voice-assistant.firebasestorage.app",
      messagingSenderId: "628271069351",
      appId: "1:628271069351:web:de5a6bb56122cc5e34c382",
      measurementId: "G-Q57C0RNWMN");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyD6_I5YiZycrIFYEYQo4jA-yIKRKjTxGzg",
    projectId: "professional-voice-assistant",
    storageBucket: "professional-voice-assistant.firebasestorage.app",
    messagingSenderId: "628271069351",
    appId: "1:628271069351:android:de5a6bb56122cc5e34c382",
  );
}
